.top-information-container {
    margin-top: 20px;
}

.chart-container {
    text-align: center;
    padding-bottom: 10px;
}

.chart-canvas {
    
}

.overview-detail-container {
    padding-top: 10px;
}

.control-label {
    width: 30%;
}

.form-control {
    display: inline;
    width: 65%;
    margin-bottom: 5px;
}

.error-text{
    color: red;
}

.edit-product{
    cursor: pointer;    
}

.remove-product{
    cursor: pointer;    
}